# Generated by Django 4.1.3 on 2022-12-13 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cont_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
