# Generated by Django 4.1.3 on 2023-02-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_abc_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abc',
            new_name='usertab',
        ),
    ]
